<a href="https://colab.research.google.com/github/MANI-WEBDEVE/RAG_SYSTEM/blob/main/RAG_CHUNK_CONCEPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

if "COLAB_GPU" in os.environ:
  print('ok')
  # !pip install -U torch # requires torch 2.1.1+ (for efficient sdpa implementation)
  !pip install PyMuPDF
  !pip install sentence-transformers # for embedding models
  !pip install tqdm
  !pip install accelerate
  !pip install bitsandbytes
  !pip install flash-attn --no-build-isolation

ok
Collecting PyMuPDF
  Downloading pymupdf-1.27.2.2-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.27.2.2-cp310-abi3-manylinux_2_28_x86_64.whl (24.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 69.6 MB/s eta 0:00:00
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.27.2.2
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.7.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.4.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (1.7.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.4.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)

In [2]:
!pip uninstall -y torch torchvision torchaudio transformers sentence-transformers
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -U transformers sentence-transformers

Found existing installation: torch 2.10.0+cu128
Uninstalling torch-2.10.0+cu128:
  Successfully uninstalled torch-2.10.0+cu128
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128
Found existing installation: transformers 5.0.0
Uninstalling transformers-5.0.0:
  Successfully uninstalled transformers-5.0.0
Found existing installation: sentence-transformers 5.3.0
Uninstalling sentence-transformers-5.3.0:
  Successfully uninstalled sentence-transformers-5.3.0
Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch
  Downloading https://download.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (780.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 MB 1.1 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download-r2.pytorch.org/whl/cu121/torchvision-0.20.1%2Bcu121-cp312-cp312-linux_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 75.5 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download-r2.pytorch.org/whl/cu121/torchaudio-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 111.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 87.4 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 64.0 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 114.6 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB ? eta 0:00:00
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.8 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.0 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 15.4 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.9 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.3 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 1.5 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 10.5 MB/s eta 0:00:00
Collecting triton==3.1.0 (from torch)
  Downloading https://download.pytorch.org/whl/triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.6/209.6 MB 6.1 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Collecting sympy==1.13.1 (from torch)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.8.93)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 82.2 MB/s eta 0:00:00
Installing collected packages: triton, sympy, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, nvidia-cudnn-cu12, torch, torchvision, torchaudio
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.8.90
    Uninstalling nvidia-nvtx-cu12-12.8.90:
      Successfully uninstalled nvidia-nvtx-cu12-12.8.90
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.27.5
    Uninstalling nvidia-nccl-cu12-2.27.5:
      Successfully uninstalled nvidia-nccl-cu12-2.27.5
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.8.93
    Uninstalling nvidia-cusparse-cu12-12.5.8.93:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.8.93
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.9.90
    Uninstalling nvidia-curand-cu12-10.3.9.90:
      Successfully uninstalled nvidia-curand-cu12-10.3.9.90
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.3.83
    Uninstalling nvidia-cufft-cu12-11.3.3.83:
      Successfully uninstalled nvidia-cufft-cu12-11.3.3.83
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.8.90
    Uninstalling nvidia-cuda-runtime-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.8.90
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.8.93
    Uninstalling nvidia-cuda-nvrtc-cu12-12.8.93:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.8.93
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.8.90
    Uninstalling nvidia-cuda-cupti-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.8.90
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.8.4.1
    Uninstalling nvidia-cublas-cu12-12.8.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.8.4.1
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.3.90
    Uninstalling nvidia-cusolver-cu12-11.7.3.90:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.3.90
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.10.2.21
    Uninstalling nvidia-cudnn-cu12-9.10.2.21:
      Successfully uninstalled nvidia-cudnn-cu12-9.10.2.21
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.18.1 requires transformers, which is not installed.
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.21.5 nvidia-nvtx-cu12-12.1.105 sympy-1.13.1 torch-2.5.1+cu121 torchaudio-2.5.1+cu121 torchvision-0.20.1+cu121 triton-3.1.0
Collecting transformers
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Collecting sentence-transformers
  Downloading sentence_transformers-5.3.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.5.1+cu121)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.4.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 46.6 MB/s eta 0:00:00
Downloading sentence_transformers-5.3.0-py3-none-any.whl (512 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.4/512.4 kB 31.5 MB/s eta 0:00:00
Installing collected packages: transformers, sentence-transformers
Successfully installed sentence-transformers-5.3.0 transformers-5.4.0

## Download the Docs

In [3]:
import os
import requests

pdf_path = "ML.pdf"

# Download pdf if doesn`t exits
if not os.path.exists(pdf_path):
  print("File does not exist")

  # The URL of the PDF of Download
  url = 'https://shashwatwork.github.io/assets/files/ml_ebook.pdf'

  filename=pdf_path

  # send the GET request to download the PDF

  response = requests.get(url)

  # check if the request was successful
  if response.status_code == 200:
    # open a file in binary write mode and save the contant it
    with open(filename, 'wb') as file:
      file.write(response.content)
    print(f'write the file has been downloaded and saved as {filename}')
  else:
    print(f'the file failed to download status code: {response.status_code}')
else:
  print(f"file {pdf_path} exists")

File does not exist
write the file has been downloaded and saved as ML.pdf

## Extract the text from documents

In [4]:
from tqdm.auto import tqdm
import fitz

def text_formater(text:str) -> str:
  """ Perform the minner formatting """
  cleaned_text=text.replace("\n", " ").strip()

  return cleaned_text
# Note: focus on only text rather than images and table

def open_and_read_pdf(pdf_path:str)->list[dict]:
  """
  Open : the pdf and read the text page by page

  Parameter get function:
    pdf_path the file path your pdf to open and read the document
  Return:
    list of and dictionary fromat [{}, {}] to return this function

  """
  docs = fitz.open(pdf_path)
  page_and_text=[]

  for page_number , page in tqdm(enumerate(docs)):
    text=page.get_text()
    text=text_formater(text)
    page_and_text.append({
        "page_number": page_number,
        "page_total_words": len(text.split(' ')),
        "page_total_char": len(text),
        "page_total_sentence": len(text.split('. ')),
        "page_total_token": len(text) /4,
        "text": text
    })

  return page_and_text


page_and_text = open_and_read_pdf(pdf_path=pdf_path)
page_and_text[:20]

0it [00:00, ?it/s]

[{'page_number': 0,
  'page_total_words': 1,
  'page_total_char': 0,
  'page_total_sentence': 1,
  'page_total_token': 0.0,
  'text': ''},
 {'page_number': 1,
  'page_total_words': 1,
  'page_total_char': 0,
  'page_total_sentence': 1,
  'page_total_token': 0.0,
  'text': ''},
 {'page_number': 2,
  'page_total_words': 30,
  'page_total_char': 237,
  'page_total_sentence': 1,
  'page_total_token': 59.25,
  'text': 'Aurélien Géron Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow Concepts, Tools, and Techniques to Build Intelligent Systems SECOND EDITION Boston Farnham Sebastopol Tokyo Beijing Boston Farnham Sebastopol Tokyo Beijing'},
 {'page_number': 3,
  'page_total_words': 249,
  'page_total_char': 1777,
  'page_total_sentence': 14,
  'page_total_token': 444.25,
  'text': '978-1-492-03264-9 [LSI] Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow by Aurélien Géron Copyright © 2019 O’Reilly Media. All rights reserved. Printed in the United States of America. Published by O’Reilly Media, Inc. , 1005 Gravenstein Highway North, Sebastopol, CA 95472. O’Reilly books may be purchased for educational, business, or sales promotional use. Online editions are also available for most titles (http://oreilly.com). For more information, contact our corporate/institutional sales department: 800-998-9938 or corporate@oreilly.com. Editor: Nicole Tache Interior Designer: David Futato Cover Designer: Karen Montgomery Illustrator: Rebecca Demarest June 2019:  Second Edition Revision History for the Early Release 2018-11-05: First Release 2019-01-24: Second Release See http://oreilly.com/catalog/errata.csp?isbn=9781492032649 for release details. The O’Reilly logo is a registered trademark of O’Reilly Media, Inc. Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow, the cover image, and related trade dress are trademarks of O’Reilly Media, Inc. While the publisher and the author have used good faith efforts to ensure that the information and instructions contained in this work are accurate, the publisher and the author disclaim all responsibility for errors or omissions, including without limitation responsibility for damages resulting from the use of or reliance on this work. Use of the information and instructions contained in this work is at your own risk. If any code samples or other technology this work contains or describes is subject to open source licenses or the intellectual property rights of others, it is your responsibility to ensure that your use thereof complies with such licenses and/or rights.'},
 {'page_number': 4,
  'page_total_words': 2467,
  'page_total_char': 3246,
  'page_total_sentence': 90,
  'page_total_token': 811.5,
  'text': 'Table of Contents 1. The Machine Learning Landscape. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  9 What Is Machine Learning?                                                                                           10 Why Use Machine Learning?                                                                                         10 Types of Machine Learning Systems                                                                             13 Supervised/Unsupervised Learning                                                                           14 Batch and Online Learning                                                                                         21 Instance-Based Versus Model-Based Learning                                                        24 Main Challenges of Machine Learning                                                                         30 Insufficient Quantity of Training Data                                                                      30 Nonrepresentative Training Data                                                                               32 Poor-Quality Data                                                                                                        33 Irrelevant Features                                                                                                        33 Overfitting the Training Data                                                                                     34 Underfitting the Training Data                                                                                  36 Stepping Back                                                                                                               36 Testing and Validating                                                                                                     37 Exercises                                                                                                                            39 2. End-to-End Machine Learning Project. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  41 Working with Real Data                                                                                                  41 Look at the Big Picture                                                                                                    43 Frame the Problem                                                                                                       43 Select a Performance Measure                                                                                    45 Check the Assumptions                                                                                               48 Get the Data                                                                                                                      48 Create the Workspace                                                                                                  48 Download the Data                                                                                                      51 Take a Quick Look at the Data Structure                                                                  53 iii'},
 {'page_number': 5,
  'page_total_words': 3766,
  'page_total_char': 4866,
  'page_total_sentence': 124,
  'page_total_token': 1216.5,
  'text': 'Create a Test Set                                                                                                            57 Discover and Visualize the Data to Gain Insights                                                       61 Visualizing Geographical Data                                                                                   62 Looking for Correlations                                                                                             64 Experimenting with Attribute Combinations                                                          67 Prepare the Data for Machine Learning Algorithms                                                  68 Data Cleaning                                                                                                               69 Handling Text and Categorical Attributes                                                                71 Custom Transformers                                                                                                  73 Feature Scaling                                                                                                              74 Transformation Pipelines                                                                                            75 Select and Train a Model                                                                                                 77 Training and Evaluating on the Training Set                                                           77 Better Evaluation Using Cross-Validation                                                                78 Fine-Tune Your Model                                                                                                    81 Grid Search                                                                                                                    81 Randomized Search                                                                                                     83 Ensemble Methods                                                                                                       84 Analyze the Best Models and Their Errors                                                               84 Evaluate Your System on the Test Set                                                                        85 Launch, Monitor, and Maintain Your System                                                              86 Try It Out!                                                                                                                         87 Exercises                                                                                                                            87 3. Classification. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  89 MNIST                                                                                                                               89 Training a Binary Classifier                                                                                            92 Performance Measures                                                                                                    92 Measuring Accuracy Using Cross-Validation                                                          93 Confusion Matrix                                                                                                         94 Precision and Recall                                                                                                     96 Precision/Recall Tradeoff                                                                                            97 The ROC Curve                                                                                                          101 Multiclass Classification                                                                                               104 Error Analysis                                                                                                                 106 Multilabel Classification                                                                                               110 Multioutput Classification                                                                                            111 Exercises                                                                                                                          112 4. Training Models. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  115 Linear Regression                                                                                                           116 The Normal Equation                                                                                                118 iv  |  Table of Contents'},
 {'page_number': 6,
  'page_total_words': 3909,
  'page_total_char': 4915,
  'page_total_sentence': 114,
  'page_total_token': 1228.75,
  'text': 'Computational Complexity                                                                                      121 Gradient Descent                                                                                                           121 Batch Gradient Descent                                                                                             125 Stochastic Gradient Descent                                                                                     128 Mini-batch Gradient Descent                                                                                   130 Polynomial Regression                                                                                                  132 Learning Curves                                                                                                             134 Regularized Linear Models                                                                                           138 Ridge Regression                                                                                                        138 Lasso Regression                                                                                                        141 Elastic Net                                                                                                                    143 Early Stopping                                                                                                            144 Logistic Regression                                                                                                        145 Estimating Probabilities                                                                                            145 Training and Cost Function                                                                                      147 Decision Boundaries                                                                                                  148 Softmax Regression                                                                                                    151 Exercises                                                                                                                          155 5. Support Vector Machines. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  157 Linear SVM Classification                                                                                            157 Soft Margin Classification                                                                                         158 Nonlinear SVM Classification                                                                                     161 Polynomial Kernel                                                                                                      162 Adding Similarity Features                                                                                       163 Gaussian RBF Kernel                                                                                                 164 Computational Complexity                                                                                      165 SVM Regression                                                                                                             166 Under the Hood                                                                                                             168 Decision Function and Predictions                                                                         168 Training Objective                                                                                                      169 Quadratic Programming                                                                                           171 The Dual Problem                                                                                                      172 Kernelized SVM                                                                                                         173 Online SVMs                                                                                                               176 Exercises                                                                                                                          177 6. Decision Trees. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  179 Training and Visualizing a Decision Tree                                                                  179 Making Predictions                                                                                                       181 Estimating Class Probabilities                                                                                      183 The CART Training Algorithm                                                                                   183 Table of Contents  |  v'},
 {'page_number': 7,
  'page_total_words': 3948,
  'page_total_char': 4918,
  'page_total_sentence': 91,
  'page_total_token': 1229.5,

In [5]:
import random
random_Sam= random.sample(page_and_text, k=5)

In [6]:
random_Sam

[{'page_number': 259,
  'page_total_words': 338,
  'page_total_char': 2124,
  'page_total_sentence': 15,
  'page_total_token': 531.0,
  'text': '>>> np.mean(y_train_partially_propagated == y_train[partially_propagated]) 0.9896907216494846 Active Learning To continue improving your model and your training set, the next step could be to do a few rounds of active learning: this is when a human expert interacts with the learn‐ ing algorithm, providing labels when the algorithm needs them. There are many dif‐ ferent strategies for active learning, but one of the most common ones is called uncertainty sampling: • The model is trained on the labeled instances gathered so far, and this model is used to make predictions on all the unlabeled instances. • The instances for which the model is most uncertain (i.e., when its estimated probability is lowest) must be labeled by the expert. • Then you just iterate this process again and again, until the performance improvement stops being worth the labeling effort. Other strategies include labeling the instances that would result in the largest model change, or the largest drop in the model’s validation error, or the instances that differ‐ ent models disagree on (e.g., an SVM, a Random Forest, and so on). Before we move on to Gaussian mixture models, let’s take a look at DBSCAN, another popular clustering algorithm that illustrates a very different approach based on local density estimation. This approach allows the algorithm to identify clusters of arbitrary shapes. DBSCAN This algorithm defines clusters as continuous regions of high density. It is actually quite simple: • For each instance, the algorithm counts how many instances are located within a small distance ε (epsilon) from it. This region is called the instance’s ε- neighborhood. • If an instance has at least min_samples instances in its ε-neighborhood (includ‐ ing itself), then it is considered a core instance. In other words, core instances are those that are located in dense regions. • All instances in the neighborhood of a core instance belong to the same cluster. This may include other core instances, therefore a long sequence of neighboring core instances forms a single cluster. 258  |  Chapter 9: Unsupervised Learning Techniques'},
 {'page_number': 241,
  'page_total_words': 453,
  'page_total_char': 2745,
  'page_total_sentence': 21,
  'page_total_token': 686.25,
  'text': '• Clustering: the goal is to group similar instances together into clusters. This is a great tool for data analysis, customer segmentation, recommender systems, search engines, image segmentation, semi-supervised learning, dimensionality reduction, and more. • Anomaly detection: the objective is to learn what “normal” data looks like, and use this to detect abnormal instances, such as defective items on a production line or a new trend in a time series. • Density estimation: this is the task of estimating the probability density function (PDF) of the random process that generated the dataset. This is commonly used for anomaly detection: instances located in very low-density regions are likely to be anomalies. It is also useful for data analysis and visualization. Ready for some cake? We will start with clustering, using K-Means and DBSCAN, and then we will discuss Gaussian mixture models and see how they can be used for density estimation, clustering, and anomaly detection. Clustering As you enjoy a hike in the mountains, you stumble upon a plant you have never seen before. You look around and you notice a few more. They are not perfectly identical, yet they are sufficiently similar for you to know that they most likely belong to the same species (or at least the same genus). You may need a botanist to tell you what species that is, but you certainly don’t need an expert to identify groups of similar- looking objects. This is called clustering: it is the task of identifying similar instances and assigning them to clusters, i.e., groups of similar instances. Just like in classification, each instance gets assigned to a group. However, this is an unsupervised task. Consider Figure 9-1: on the left is the iris dataset (introduced in Chapter 4), where each instance’s species (i.e., its class) is represented with a different marker. It is a labeled dataset, for which classification algorithms such as Logistic Regression, SVMs or Random Forest classifiers are well suited. On the right is the same dataset, but without the labels, so you cannot use a classification algorithm any‐ more. This is where clustering algorithms step in: many of them can easily detect the top left cluster. It is also quite easy to see with our own eyes, but it is not so obvious that the lower right cluster is actually composed of two distinct sub-clusters. That said, the dataset actually has two additional features (sepal length and width), not represented here, and clustering algorithms can make good use of all features, so in fact they identify the three clusters fairly well (e.g., using a Gaussian mixture model, only 5 instances out of 150 are assigned to the wrong cluster). 240  |  Chapter 9: Unsupervised Learning Techniques'},
 {'page_number': 120,
  'page_total_words': 192,
  'page_total_char': 1119,
  'page_total_sentence': 6,
  'page_total_token': 279.75,
  'text': 'Figure 4-1. Randomly generated linear dataset Now let’s compute θ using the Normal Equation. We will use the inv() function from NumPy’s Linear Algebra module (np.linalg) to compute the inverse of a matrix, and the dot() method for matrix multiplication: X_b = np.c_[np.ones((100, 1)), X]  # add x0 = 1 to each instance theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y) The actual function that we used to generate the data is y = 4 + 3x1 + Gaussian noise. Let’s see what the equation found: >>> theta_best array([[4.21509616],        [2.77011339]]) We would have hoped for θ0 = 4 and θ1 = 3 instead of θ0 = 4.215 and θ1 = 2.770. Close enough, but the noise made it impossible to recover the exact parameters of the origi‐ nal function. Now you can make predictions using θ: >>> X_new = np.array([[0], [2]]) >>> X_new_b = np.c_[np.ones((2, 1)), X_new] # add x0 = 1 to each instance >>> y_predict = X_new_b.dot(theta_best) >>> y_predict array([[4.21509616],        [9.75532293]]) Let’s plot this model’s predictions (Figure 4-2): plt.plot(X_new, y_predict, "r-") plt.plot(X, y, "b.") Linear Regression  |  119'},
 {'page_number': 10,
  'page_total_words': 340,
  'page_total_char': 2015,
  'page_total_sentence': 12,
  'page_total_token': 503.75,
  'text': 'CHAPTER 1 The Machine Learning Landscape When most people hear “Machine Learning,” they picture a robot: a dependable but‐ ler or a deadly Terminator depending on who you ask. But Machine Learning is not just a futuristic fantasy, it’s already here. In fact, it has been around for decades in some specialized applications, such as Optical Character Recognition (OCR). But the first ML application that really became mainstream, improving the lives of hundreds of millions of people, took over the world back in the 1990s: it was the spam filter. Not exactly a self-aware Skynet, but it does technically qualify as Machine Learning (it has actually learned so well that you seldom need to flag an email as spam any‐ more). It was followed by hundreds of ML applications that now quietly power hun‐ dreds of products and features that you use regularly, from better recommendations to voice search. Where does Machine Learning start and where does it end? What exactly does it mean for a machine to learn something? If I download a copy of Wikipedia, has my computer really “learned” something? Is it suddenly smarter? In this chapter we will start by clarifying what Machine Learning is and why you may want to use it. Then, before we set out to explore the Machine Learning continent, we will take a look at the map and learn about the main regions and the most notable landmarks: supervised versus unsupervised learning, online versus batch learning, instance- based versus model-based learning. Then we will look at the workflow of a typical ML project, discuss the main challenges you may face, and cover how to evaluate and fine-tune a Machine Learning system. This chapter introduces a lot of fundamental concepts (and jargon) that every data scientist should know by heart. It will be a high-level overview (the only chapter without much code), all rather simple, but you should make sure everything is crystal-clear to you before continuing to the rest of the book. So grab a coffee and let’s get started! 9'},
 {'page_number': 151,
  'page_total_words': 344,
  'page_total_char': 2040,
  'page_total_sentence': 13,
  'page_total_token': 510.0,
  'text': '18 It is the the set of points x such that θ0 + θ1x1 + θ2x2 = 0, which defines a straight line. plt.plot(X_new, y_proba[:, 0], "b--", label="Not Iris-Virginica") # + more Matplotlib code to make the image look pretty Figure 4-23. Estimated probabilities and decision boundary The petal width of Iris-Virginica flowers (represented by triangles) ranges from 1.4 cm to 2.5 cm, while the other iris flowers (represented by squares) generally have a smaller petal width, ranging from 0.1 cm to 1.8 cm. Notice that there is a bit of over‐ lap. Above about 2 cm the classifier is highly confident that the flower is an Iris- Virginica (it outputs a high probability to that class), while below 1 cm it is highly confident that it is not an Iris-Virginica (high probability for the “Not Iris-Virginica” class). In between these extremes, the classifier is unsure. However, if you ask it to predict the class (using the predict() method rather than the predict_proba() method), it will return whichever class is the most likely. Therefore, there is a decision boundary at around 1.6 cm where both probabilities are equal to 50%: if the petal width is higher than 1.6 cm, the classifier will predict that the flower is an Iris- Virginica, or else it will predict that it is not (even if it is not very confident): >>> log_reg.predict([[1.7], [1.5]]) array([1, 0]) Figure 4-24 shows the same dataset but this time displaying two features: petal width and length. Once trained, the Logistic Regression classifier can estimate the probabil‐ ity that a new flower is an Iris-Virginica based on these two features. The dashed line represents the points where the model estimates a 50% probability: this is the model’s decision boundary. Note that it is a linear boundary.18 Each parallel line represents the points where the model outputs a specific probability, from 15% (bottom left) to 90% (top right). All the flowers beyond the top-right line have an over 90% chance of being Iris-Virginica according to the model. 150  |  Chapter 4: Training Models'}]

In [7]:
import pandas as pd

df=pd.DataFrame(page_and_text)

In [8]:
df

,page_number,page_total_words,page_total_char,page_total_sentence,page_total_token,text
0,0,1,0,1,0.00,
1,1,1,0,1,0.00,
2,2,30,237,1,59.25,Aurélien Géron Hands-on Machine Learning with ...
3,3,249,1777,14,444.25,978-1-492-03264-9 [LSI] Hands-on Machine Learn...
4,4,2467,3246,90,811.50,Table of Contents 1. The Machine Learning Land...
...,...,...,...,...,...,...
274,274,190,1131,10,282.75,Figure 9-22. Bayesian Gaussian mixture model P...
275,275,350,1771,13,442.75,Bayes’ theorem (Equation 9-2) tells us how to ...
276,276,363,2263,15,565.75,"In practice, there are different techniques to..."
277,277,440,2785,19,696.25,Other Anomaly Detection and Novelty Detection ...
278,278,454,2728,21,682.00,About the Author Aurélien Géron is a Machine L...

In [9]:
df.describe()

,page_number,page_total_words,page_total_char,page_total_sentence,page_total_token
count,279.000000,279.000000,279.000000,279.000000,279.000000
mean,139.000000,335.738351,1750.713262,13.591398,437.678315
std,80.684571,408.443051,691.596170,12.272303,172.899043
min,0.000000,1.000000,0.000000,1.000000,0.000000
25%,69.500000,222.000000,1367.500000,9.000000,341.875000
50%,139.000000,302.000000,1786.000000,12.000000,446.500000
75%,208.500000,356.500000,2124.500000,15.000000,531.125000
max,278.000000,3948.000000,4918.000000,124.000000,1229.500000

## Step no 3 Chunking Section
---
How to implement five methods of chunking. Fixed , Semantic , structural , recursive, LLM based.

## First Method is Fixed size of Chunk our data

In [10]:
def chunk_size(text:str, chunk_size:int = 500) -> list:
  """
  Split the text to chunk size.
  """

  chunks=[]
  words=text.split()
  current_chunk=""

  for word in words:
    # if check the word before adding excced chunk
    if len(current_chunk) + len(word) + 2 <= chunk_size:
      current_chunk += (word + " ")
    else:
      chunks.append(current_chunk.strip())
      current_chunk += word + " "

  if current_chunk:
      chunks.append(current_chunk.strip())

  return chunks

In [11]:
chunk_ex = []
current_chunk_ex = ""

ex_word = "this is my car"

In [12]:
for word in ex_word.split():
  if len(current_chunk_ex) + len(word) + 1 <= 3:
    print(word)
    current_chunk_ex += (word + " ")
    print(word + " ")
  else :
    print('lo')

lo
is
is
lo
lo

In [13]:
current_chunk_ex

'is '

In [14]:
chunk_ex.append(ex_word.split())

In [15]:
chunk_ex

[['this', 'is', 'my', 'car']]

## Method Semantic Chunking

In [16]:
!pip install -q --upgrade "sentence-transformers==3.0.1" "transformers<5, >4.41" scikit-learn nltk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 164.1 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 33.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 30.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 51.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 19.6 MB/s eta 0:00:00

In [17]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import nltk
nltk.download('punkt_tab', quiet=True)

# load model locally

semantic_model=SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

def semantic_chunk_text(text:str, similarity_threshold=0.8, max_token=500)-> list:

  sentence = nltk.sent_tokenize(text)

  if not sentence:
    return []

  embeddings=semantic_model.encode(sentence)

  chunks=[]
  current_chunk=[sentence[0]]
  current_embedding=embeddings[0]

  for i in range(1, len(sentence)):
    sim=cosine_similarity([current_embedding], [embeddings[i]])[0][0]
    chunk_token_count=len(" ".join(current_chunk)) // 4

    if sim >= similarity_threshold and chunk_token_count < max_token:
      current_chunk.append(sentence[i])
      current_embedding = np.mean([current_embedding, embeddings[i]], axis=0)
    else:
      chunks.append(" ".join(current_chunk))
      current_chunk = [sentence[i]]
      current_embedding=embeddings[i]

  if current_chunk:
    chunks.append(" ".join(current_chunk))
  return chunks

from tqdm.auto import tqdm

def semantic_chunk_pdf_pages(page_and_text:list, similarity_threshod:float=0.8, max_token:int=500)-> list[dict]:
    all_chunks=[]

    for page in tqdm(page_and_text, desc="semantic chunking pages"):
      page_number=page['page_number']
      page_text=page['text']

      chunks= semantic_chunk_text(
          page_text,
          similarity_threshold=similarity_threshod,
          max_token=max_token
      )

      for i , chunk in enumerate(chunks):
        all_chunks.append(
            {
                'page_number':page_number,
                'chunk_index': i,
                'chunk_char_count': len(chunk),
                'chunk_word_count': len(chunk.split()),
                'chunk_token_count': len(chunk) / 4,
                'chunk_text': chunk
            }
        )
    return all_chunks
import nltk
nltk.download('punkt_tab', quiet=True)
semactic_chunks = semantic_chunk_pdf_pages(page_and_text, similarity_threshod=0.8, max_token=500)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

semantic chunking pages:   0%|          | 0/279 [00:00<?, ?it/s]

In [18]:
len(semactic_chunks)

3461

In [19]:
total_chunk=0
for i in semactic_chunks:
  print(i)

{'page_number': 2, 'chunk_index': 0, 'chunk_char_count': 237, 'chunk_word_count': 30, 'chunk_token_count': 59.25, 'chunk_text': 'Aurélien Géron Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow Concepts, Tools, and Techniques to Build Intelligent Systems SECOND EDITION Boston Farnham Sebastopol Tokyo Beijing Boston Farnham Sebastopol Tokyo Beijing'}
{'page_number': 3, 'chunk_index': 0, 'chunk_char_count': 141, 'chunk_word_count': 18, 'chunk_token_count': 35.25, 'chunk_text': '978-1-492-03264-9 [LSI] Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow by Aurélien Géron Copyright © 2019 O’Reilly Media.'}
{'page_number': 3, 'chunk_index': 1, 'chunk_char_count': 20, 'chunk_word_count': 3, 'chunk_token_count': 5.0, 'chunk_text': 'All rights reserved.'}
{'page_number': 3, 'chunk_index': 2, 'chunk_char_count': 40, 'chunk_word_count': 7, 'chunk_token_count': 10.0, 'chunk_text': 'Printed in the United States of America.'}
{'page_number': 3, 'chunk_index': 3, 'chunk_char_count': 89, 'chunk_word_count': 13, 'chunk_token_count': 22.25, 'chunk_text': 'Published by O’Reilly Media, Inc. , 1005 Gravenstein Highway North, Sebastopol, CA 95472.'}
{'page_number': 3, 'chunk_index': 4, 'chunk_char_count': 84, 'chunk_word_count': 12, 'chunk_token_count': 21.0, 'chunk_text': 'O’Reilly books may be purchased for educational, business, or sales promotional use.'}
{'page_number': 3, 'chunk_index': 5, 'chunk_char_count': 72, 'chunk_word_count': 9, 'chunk_token_count': 18.0, 'chunk_text': 'Online editions are also available for most titles (http://oreilly.com).'}
{'page_number': 3, 'chunk_index': 6, 'chunk_char_count': 114, 'chunk_word_count': 11, 'chunk_token_count': 28.5, 'chunk_text': 'For more information, contact our corporate/institutional sales department: 800-998-9938 or corporate@oreilly.com.'}
{'page_number': 3, 'chunk_index': 7, 'chunk_char_count': 316, 'chunk_word_count': 35, 'chunk_token_count': 79.0, 'chunk_text': 'Editor: Nicole Tache Interior Designer: David Futato Cover Designer: Karen Montgomery Illustrator: Rebecca Demarest June 2019:  Second Edition Revision History for the Early Release 2018-11-05: First Release 2019-01-24: Second Release See http://oreilly.com/catalog/errata.csp?isbn=9781492032649 for release details.'}
{'page_number': 3, 'chunk_index': 8, 'chunk_char_count': 215, 'chunk_word_count': 32, 'chunk_token_count': 53.75, 'chunk_text': 'The O’Reilly logo is a registered trademark of O’Reilly Media, Inc. Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow, the cover image, and related trade dress are trademarks of O’Reilly Media, Inc.'}
{'page_number': 3, 'chunk_index': 9, 'chunk_char_count': 338, 'chunk_word_count': 52, 'chunk_token_count': 84.5, 'chunk_text': 'While the publisher and the author have used good faith efforts to ensure that the information and instructions contained in this work are accurate, the publisher and the author disclaim all responsibility for errors or omissions, including without limitation responsibility for damages resulting from the use of or reliance on this work.'}
{'page_number': 3, 'chunk_index': 10, 'chunk_char_count': 83, 'chunk_word_count': 15, 'chunk_token_count': 20.75, 'chunk_text': 'Use of the information and instructions contained in this work is at your own risk.'}
{'page_number': 3, 'chunk_index': 11, 'chunk_char_count': 254, 'chunk_word_count': 41, 'chunk_token_count': 63.5, 'chunk_text': 'If any code samples or other technology this work contains or describes is subject to open source licenses or the intellectual property rights of others, it is your responsibility to ensure that your use thereof complies with such licenses and/or rights.'}
{'page_number': 4, 'chunk_index': 0, 'chunk_char_count': 20, 'chunk_word_count': 4, 'chunk_token_count': 5.0, 'chunk_text': 'Table of Contents 1.'}
{'page_number': 4, 'chunk_index': 1, 'chunk_char_count': 31, 'chunk_word_count': 4, 'chunk_token_count': 7.75, 'chunk_text': 'The Machine Learning Landscape.'}
{'page_number': 4, 'chunk_index': 2, 'chunk_char_count': 89, 'chunk_word_count': 45, 'chunk_token_count': 22.25, 'chunk_text': '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .'}
{'page_number': 4, 'chunk_index': 3, 'chunk_char_count': 27, 'chunk_word_count': 5, 'chunk_token_count': 6.75, 'chunk_text': '9 What Is Machine Learning?'}
{'page_number': 4, 'chunk_index': 4, 'chunk_char_count': 28, 'chunk_word_count': 5, 'chunk_token_count': 7.0, 'chunk_text': '10 Why Use Machine Learning?'}
{'page_number': 4, 'chunk_index': 5, 'chunk_char_count': 1652, 'chunk_word_count': 62, 'chunk_token_count': 413.0, 'chunk_text': '10 Types of Machine Learning Systems                                                                             13 Supervised/Unsupervised Learning                                                                           14 Batch and Online Learning                                                                                         21 Instance-Based Versus Model-Based Learning                                                        24 Main Challenges of Machine Learning                                                                         30 Insufficient Quantity of Training Data                                                                      30 Nonrepresentative Training Data                                                                               32 Poor-Quality Data                                                                                                        33 Irrelevant Features                                                                                                        33 Overfitting the Training Data                                                                                     34 Underfitting the Training Data                                                                                  36 Stepping Back                                                                                                               36 Testing and Validating                                                                                                     37 Exercises                                                                                                                            39 2.'}
{'page_number': 4, 'chunk_index': 6, 'chunk_char_count': 36, 'chunk_word_count': 4, 'chunk_token_count': 9.0, 'chunk_text': 'End-to-End Machine Learning Project.'}
{'page_number': 4, 'chunk_index': 7, 'chunk_char_count': 79, 'chunk_word_count': 40, 'chunk_token_count': 19.75, 'chunk_text': '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .'}
{'page_number': 4, 'chunk_index': 8, 'chunk_char_count': 1096, 'chunk_word_count': 47, 'chunk_token_count': 274.0, 'chunk_text': '41 Working with Real Data                                                                                                  41 Look at the Big Picture                                                                                                    43 Frame the Problem                                                                                                       43 Select a Performance Measure                                                                                    45 Check the Assumptions                                                                                               48 Get the Data                                                                                                                      48 Create the Workspace                                                                                                  48 Download the Data                                                                                                      51 Take a Quick Look at the Data Structure                                                                  53 iii'}
{'page_number': 5, 'chunk_index': 0, 'chunk_char_count': 2439, 'chunk_word_count': 111, 'chunk_token_count': 609.75, 'chunk_text': 'Create a Test Set                                                                                                            57 Discover and Visualize the Data to Gain Insights                                                       61 Visualizing Geographical Data                                                                                   62 Looking for Correlations                                                                                             64 Experimenting with Attribute Combinations                                                          67 Prepare the Data for Machine Learning Algorithms                                                  68 Data Cleaning                                                                                                               69 Handling Text and Categorical Attributes                                                                71 Custom Transformers                                                                                                  73 Feature Scaling                                                                                                              74 Transformation Pipelines                                                                                            75 Select and Train a Model                                                                                                 77 Training and Evaluating on the Training Set                                                           77 Better Evaluation Using Cross-Validation                                                                78 Fine-Tune Your Model                                                                                                    81 Grid Search                                                                                                                    81 Randomized Search                                                                                                     83 Ensemble Methods                                                                                                       84 Analyze the Best Models and Their Errors                                                               84 Evaluate Your System on the Test Set                                                                        85 Launch, Monitor, and Maintain Your System                                                              86 Try It Out!'}
{'page_number': 5, 'chunk_index': 1, 'chunk_char_count': 141, 'chunk_word_count': 4, 'chunk_token_count': 35.25, 'chunk_text': '87 Exercises                                                                                                                            87 3.'}
{'page_number': 5, 'chunk_index': 2, 'chunk_char_count': 15, 'chunk_word_count': 1, 'chunk_token_count': 3.75, 'chunk_text': 'Classification.'}
{'page_number': 5, 'chunk_index': 3, 'chunk_char_count': 121, 'chunk_word_count': 61, 'chunk_token_count': 30.25, 'chunk_text': '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .'}
{'page_number': 5, 'chunk_index': 4, 'chunk_char_count': 1615, 'chunk_word_count': 45, 'chunk_token_count': 403.75, 'chunk_text': '89 MNIST                                                                                                                               89 Training a Binary Classifier                                                                                            92 Performance Measures                                                                                                    92 Measuring Accuracy Using Cross-Validation                                                          93 Confusion Matrix                                                                                                         94 Precision and Recall                                                                                                     96 Precision/Recall Tradeoff                                                                                            97 The ROC Curve                                                                                                          101 Multiclass Classification                                                                                               104 Error Analysis                                                                                                                 106 Multilabel Classification                                                                                               110 Multioutput Classification                                                                                            111 Exercises                                                                                                                          112 4.'}
{'page_number': 5, 'chunk_index': 5, 'chunk_char_count': 16, 'chunk_word_count': 2, 'chunk_token_count': 4.0, 'chunk_text': 'Training Models.'}
{'page_number': 5, 'chunk_index': 6, 'chunk_char_count': 115, 'chunk_word_count': 58, 'chunk_token_count': 28.75, 'chunk_text': '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .'}
{'page_number': 5, 'chunk_index': 7, 'chunk_char_count': 275, 'chunk_word_count': 13, 'chunk_token_count': 68.75, 'chunk_text': '115 Linear Regression                                                                                                           116 The Normal Equation                                                                                                118 iv  |  Table of Contents'}
{'page_number': 6, 'chunk_index': 0, 'chunk_char_count': 2209, 'chunk_word_count': 60, 'chunk_token_count': 552.25, 'chunk_text': 'Computational Complexity                                                                                      121 Gradient Descent                                                                                                           121 Batch Gradient Descent                                                                                             125 Stochastic Gradient Descent                                                                                     128 Mini-batch Gradient Descent                                                                                   130 Polynomial Regression                                                                                                  132 Learning Curves                                                                                                             134 Regularized Linear Models                                                                                           138 Ridge Regression                                                                                                        138 Lasso Regression                                                                                                        141 Elastic Net                                                                                                                    143 Early Stopping                                                                                                            144 Logistic Regression                                                                                                        145 Estimating Probabilities                                                                                            145 Training and Cost Function                                                                                      147 Decision Boundaries                                                                                                  148 Softmax Regression                                                                                                    151 Exercises                                                                                                                          155 5.'}
{'page_number': 6, 'chunk_index': 1, 'chunk_char_count': 24, 'chunk_word_count': 3, 'chunk_token_count': 6.0, 'chunk_text': 'Support Vector Machines.'}
{'page_number': 6, 'chunk_index': 2, 'chunk_char_count': 99, 'chunk_word_count': 50, 'chunk_token_count': 24.75, 'chunk_text': '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .'}
{'page_number': 6, 'chunk_index': 3, 'chunk_char_count': 1947, 'chunk_word_count': 58, 'chunk_token_count': 486.75, 'chunk_text': '157 Linear SVM Classification                                                                                            157 Soft Margin Classification                                                                                         158 Nonlinear SVM Classification                                                                                     161 Polynomial Kernel                                                                                                      162 Adding Similarity Features                                                                                       163 Gaussian RBF Kernel                                                                                                 164 Computational Complexity                                                                                      165 SVM Regression                                                                                                             166 Under the Hood                                                                                                             168 Decision Function and Predictions                                                                         168 Training Objective                                                                                                      169 Quadratic Programming                                                                                           171 The Dual Problem                                                                                                      172 Kernelized SVM                                                                                                         173 Online SVMs                                                                                                               176 Exercises                                                                                                                          177 6.'}
{'page_number': 6, 'chunk_index': 4, 'chunk_char_count': 15, 'chunk_word_count': 2, 'chunk_token_count': 3.75, 'chunk_text': 'Decision Trees.'}
{'page_number': 6, 'chunk_index': 5, 'chunk_char_count': 117, 'chunk_word_count': 59, 'chunk_token_count': 29.25, 'chunk_text': '. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .'}
{'page_number': 6, 'chunk_index': 6, 'chunk_char_count': 496, 'chunk_word_count': 25, 'chunk_token_count': 124.0, 'chunk_text': '179 Training and Visualizing a Decision Tree                                                                  179 Making Predictions                                                                                                       181 Estimating Class Probabilities                                                                                      183 The CART Training Algorithm                                                                                   183 Table of Contents  |  v'}
{'page_number': 7, 'chunk_index': 0, 'chunk_char_count': 143, 'chunk_word_count': 7, 'chunk_token_count': 35.75, 'chunk_text': 'Computational Complexity                                                                                          184 Gini Impurity or Entropy?'}

In [20]:
se=nltk.sent_tokenize(page_and_text[3]['text'])

In [21]:
semantic_model.encode(se)

array([[-0.08356416, -0.10359119,  0.05468197, ...,  0.01103478,
        -0.07604165,  0.01905698],
       [ 0.0043254 ,  0.03656445, -0.06567881, ...,  0.02435147,
        -0.05985817,  0.02358041],
       [-0.02225668,  0.06076472, -0.10556878, ..., -0.0474557 ,
         0.0873454 ,  0.01436314],
       ...,
       [-0.08282682,  0.12455787,  0.04454409, ..., -0.01990742,
         0.03544137, -0.05798681],
       [-0.04362151,  0.07473563, -0.05297586, ...,  0.03542088,
         0.02321107, -0.04479911],
       [-0.10693968,  0.00704439, -0.08952145, ...,  0.06513036,
         0.05043962, -0.09322445]], dtype=float32)

In [22]:
page_and_text[23]

{'page_number': 23,
 'page_total_words': 314,
 'page_total_char': 1757,
 'page_total_sentence': 14,
 'page_total_token': 439.25,
 'text': 'batch learning system can adapt to change. Simply update the data and train a new version of the system from scratch as often as needed. This solution is simple and often works fine, but training using the full set of data can take many hours, so you would typically train a new system only every 24 hours or even just weekly. If your system needs to adapt to rapidly changing data (e.g., to pre‐ dict stock prices), then you need a more reactive solution. Also, training on the full set of data requires a lot of computing resources (CPU, memory space, disk space, disk I/O, network I/O, etc.). If you have a lot of data and you automate your system to train from scratch every day, it will end up costing you a lot of money. If the amount of data is huge, it may even be impossible to use a batch learning algorithm. Finally, if your system needs to be able to learn autonomously and it has limited resources (e.g., a smartphone application or a rover on Mars), then carrying around large amounts of training data and taking up a lot of resources to train for hours every day is a showstopper. Fortunately, a better option in all these cases is to use algorithms that are capable of learning incrementally. Online learning In online learning, you train the system incrementally by feeding it data instances sequentially, either individually or by small groups called mini-batches. Each learning step is fast and cheap, so the system can learn about new data on the fly, as it arrives (see Figure 1-13). Figure 1-13. Online learning Online learning is great for systems that receive data as a continuous flow (e.g., stock prices) and need to adapt to change rapidly or autonomously. It is also a good option 22  |  Chapter 1: The Machine Learning Landscape'}

## Sturctural Chunking

In [54]:
import random
import textwrap
import re
# 1) Helper to detect "chapter start" pages
def _is_chapter_header_page(text: str) -> bool:
    """Detects chapter headers like 'Chapter 1:', 'Chapter 2:' etc."""
    return re.search(r"chapter\s+\d+", text, flags=re.IGNORECASE) is not None

def _guess_title_from_page(text: str) -> str:
    """Extracts chapter title from page text"""
    # Option 1: If format is "Chapter X: Title"
    m = re.search(r"chapter\s+\d+:\s*(.+)", text, flags=re.IGNORECASE)
    if m:
        return m.group(1).strip()

    # Option 2: First line as title
    lines = text.strip().split('\n')
    if lines:
        return lines[0].strip()

    # Fallback
    return "Untitled chapter"

In [55]:
# 2) Build chapter chunks
def chapter_chunk_pdf_pages(pages_and_texts: list[dict]) -> list[dict]:
    """
    Returns a list of chapter chunks:
    [
        {
            'chapter_index': int,
            'title': str,
            'page_start': int,  # adjusted page number (your -41 offset)
            'page_end': int,
            'chunk_char_count': int,
            'chunk_word_count': int,
            '# ~chars/4
            'chunk_token_count': float,  # round(len(all_text) / 4, 2),
            'chunk_text': str
        },
        ...
    ]
    """
    if not pages_and_texts:
        return []

    # Treat entire doc as one "chapter" if no headers found
    all_text = " ".join(p["text"] for p in pages_and_texts).strip()
    if not _is_chapter_header_page(all_text):
        return [{
            "chapter_index": 0,
            "title": _guess_title_from_page(pages_and_texts[0]["text"]),
            "page_start": pages_and_texts[0]["page_number"],
            "page_end": pages_and_texts[-1]["page_number"],
            "chunk_char_count": len(all_text),
            "chunk_word_count": len(all_text.split()),
            "chunk_token_count": round(len(all_text) / 4, 2),
            "chunk_text": all_text
        }]

    # Find all page indices that look like the start of a chapter
    chapter_starts = []
    for i, p in enumerate(pages_and_texts):
        txt = p["text"].strip()
        if _is_chapter_header_page(txt):
            chapter_starts.append(i)

    # Build chapter ranges (start -> next_start-1)
    chapter_chunks = []
    for ci, s in enumerate(chapter_starts):
        e = chapter_starts[ci + 1] - 1 if (ci + 1 < len(chapter_starts)) else (len(pages_and_texts) - 1)
        if e < s:  # guard (shouldn't happen)
            continue

        pages = pages_and_texts[s:e + 1]
        text_concat = " ".join(p["text"] for p in pages).strip()
        title = _guess_title_from_page(pages[0]["text"])

        chapter_chunks.append({
            "chapter_index": ci,
            "title": title,
            "page_start": pages[0]["page_number"],
            "page_end": pages[-1]["page_number"],
            "chunk_char_count": len(text_concat),
            "chunk_word_count": len(text_concat.split()),
            "chunk_token_count": round(len(text_concat) / 4, 2),
            "chunk_text": text_concat
        })

    return chapter_chunks

In [53]:
len(structural_chunks)

3

In [56]:
structure_chunked_pages = chapter_chunk_pdf_pages(page_and_text)

print(f"Total chapter-based chunks: {len(structure_chunked_pages)}")

if structure_chunked_pages:
    first = structure_chunked_pages[120]
    print(f"First chapter pages ({first['page_start']}-{first['page_end']}): {first['title']}")
    print(f"  {first['chunk_text'][:]} + \"...\"")
else:
    print("No chapters detected.")

Total chapter-based chunks: 158
First chapter pages (211-212): Ensemble Learning and Random Forests
  Figure 7-10. GBRT ensembles with not enough predictors (left) and too many (right) In order to find the optimal number of trees, you can use early stopping (see Chap‐ ter 4). A simple way to implement this is to use the staged_predict() method: it returns an iterator over the predictions made by the ensemble at each stage of train‐ ing (with one tree, two trees, etc.). The following code trains a GBRT ensemble with 120 trees, then measures the validation error at each stage of training to find the opti‐ mal number of trees, and finally trains another GBRT ensemble using the optimal number of trees: import numpy as np from sklearn.model_selection import train_test_split from sklearn.metrics import mean_squared_error X_train, X_val, y_train, y_val = train_test_split(X, y) gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=120) gbrt.fit(X_train, y_train) errors = [mean_squared_error(y_val, y_pred)           for y_pred in gbrt.staged_predict(X_val)] bst_n_estimators = np.argmin(errors) gbrt_best = GradientBoostingRegressor(max_depth=2,n_estimators=bst_n_estimators) gbrt_best.fit(X_train, y_train) The validation errors are represented on the left of Figure 7-11, and the best model’s predictions are represented on the right. 210  |  Chapter 7: Ensemble Learning and Random Forests Figure 7-11. Tuning the number of trees using early stopping It is also possible to implement early stopping by actually stopping training early (instead of training a large number of trees first and then looking back to find the optimal number). You can do so by setting warm_start=True, which makes Scikit- Learn keep existing trees when the fit() method is called, allowing incremental training. The following code stops training when the validation error does not improve for five iterations in a row: gbrt = GradientBoostingRegressor(max_depth=2, warm_start=True) min_val_error = float("inf") error_going_up = 0 for n_estimators in range(1, 120):     gbrt.n_estimators = n_estimators     gbrt.fit(X_train, y_train)     y_pred = gbrt.predict(X_val)     val_error = mean_squared_error(y_val, y_pred)     if val_error < min_val_error:         min_val_error = val_error         error_going_up = 0     else:         error_going_up += 1         if error_going_up == 5:             break  # early stopping The GradientBoostingRegressor class also supports a subsample hyperparameter, which specifies the fraction of training instances to be used for training each tree. For example, if subsample=0.25, then each tree is trained on 25% of the training instan‐ ces, selected randomly. As you can probably guess by now, this trades a higher bias for a lower variance. It also speeds up training considerably. This technique is called Stochastic Gradient Boosting. Boosting  |  211 + "..."